### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by andreasmeid** [levenc/posologyr#36]
Dear Cyril,

I receive the error message "Error: $ operator is invalid for atomic vectors" upon running the function poso_estim_map. I tried to find out what is wrong by myself, but I don't make any actual progress. Looking into the function
  object$solved_ppk_model

yields the message  

  Error in rxIs(x, "rxSolve") : 
    Cannot convert object to an environment: [type=NULL; target=ENVSXP].

but I don't really know if this might be the reason. Maybe other packages (or their version) infers with something in poso_estim_map? Could you please take a look at the attached code, I really have no clue how to fix this problem. 

Many thanks and best wishes
Andreas
[Wu_example.txt](https://github.com/levenc/posologyr/files/11462901/Wu_example.txt)

**Comment by levenc** [comment]
Dear @andreasmeid ,
Thank you for the code example. Unfortunately I could not reproduce your problem: for me your code works perfectly.
See below a slightly modified version (I usually create the list in a separate object before calling posologyr, but your approach works too), we get a good estimate, and the graph is encouraging.

```r
# Example from CPTPharmacometricsSystPharmacol12_1_e17_Wu_23887441

mod_Wu <- list(
  ppk_model = rxode2::rxode2({
  
  CL1=(TVCL*(0.3509/HCT)^BETA_HCT)*exp(eta.CL1);
  V1=TVV1*exp(eta.V1);
  CL2=TVCL2*exp(eta.CL2);
  V2=TVV2*exp(eta.V2);
  EMAX=TVEMAX; # Vm
  TMAX=TVTMAX; # Km
  K=CL1/V1;
  K12=CL2/V1;
  K21=CL2/V2;
  S2=V1/1000;
  
  d/dt(A1)=-EMAX*A1/(TMAX+A1);
  d/dt(A2)=EMAX*A1/(TMAX+A1)-K*A2-K12*A2+K21*A3;
  d/dt(A3)=K12*A2-K21*A3;
  
  Cc=A2/V1*1000;
  
}),
error_model = function(f,sigma){
  g <- sigma[1] + sigma[2]*f
  return(g)
},
theta = c(TVCL=12.9, #L/h
          BETA_HCT=0.14,# 0 wenn kein Haematokrit vorhanden
          HCT=0.3509,
          TVV1=53.4, # L
          TVCL2=29.0, #L/h
          TVV2=611,#L
          TVEMAX=13.8,
          TVTMAX=4.56),
omega = lotri::lotri({eta.CL1 + eta.V1 + eta.CL2 + eta.V2 ~
    c(0.524^2,
      0      , 0.524^2,
      0      , 0   ,  0.705^2,
      0      , 0   ,  0,   0.193^2 )}),
sigma       = c(additive_a = 0.5, proportional_b = 0.0217))

library(dplyr)
Wu_obs_8mg <- tibble::tribble(
  ~time, ~ DV, 
  0.953, 17.914,
  1.845, 26.194,
  4.224, 18.151,
  7.886, 11.779,
  24.445, 5.367,
  47.032, 2.611
) %>% as.data.frame() %>% dplyr::rename(TIME=time) %>% mutate(ID=1, AMT=0,  EVID=0) %>%
  dplyr::select(ID,TIME, DV, AMT, EVID)

admin <- rbind(data.frame(ID=1, TIME=0, DV=NA, AMT=8, EVID=1))

Wu_data_8mg <- rbind(admin, Wu_obs_8mg)

poso_Wu_8mg <- posologyr::poso_estim_map(dat=as.data.frame(Wu_data_8mg),
                              prior_model=mod_Wu)

## plot with data
indiv_obs           <- Wu_data_8mg[,c("DV","TIME")]
names(indiv_obs)    <- c("value","time")

plot(poso_Wu_8mg$model,Cc) +
  ggplot2::ylab("Central concentration") +
  ggplot2::geom_point(data=indiv_obs, size= 3, na.rm=TRUE)
```

![Rplot](https://github.com/levenc/posologyr/assets/62027274/eba16c9c-b7c8-4a29-b44e-fcb670100829)

Do you have the latest version of the different packages? rxode2 and data.table are particularly important for the proper functioning of posologyr. You can update posologyr with the following command if needed.

```r
# install.packages("remotes")
remotes::install_github("levenc/posologyr")
```

**Comment by andreasmeid** [comment]
Dear Cyril,

many thanks for checking. I strongly suppose that it has to do with other packages and their versions. I installed R (and only mandatory packages for posologyr) again and now it works, indeed.

At the moment, this seems to be the (only?) solution to the problem.

Best wishes

Andreas

**Comment by levenc** [comment]
Dear Andreas,

You're welcome! I'm glad to hear that reinstalling R and the necessary packages for posologyr resolved the issue for you. It's not uncommon for package conflicts or version mismatches to cause such problems.

If you encounter any further issues or have any more questions, please don't hesitate to reach out. I'm here to assist you.

Best wishes,
Cyril
