### ISSUE TITLE
Import models from NONMEM

### ISSUE THREAD

**Issue by mattfidler** [levenc/posologyr#42]
It would be great to import models from NONMEM using `nonmem2rx`:

https://github.com/nlmixr2/nonmem2rx

Some basic functions could convert models to the format you have in this package.

If you are going to PAGE, stop by the `nonmem2rx` poster and maybe we can discuss (if you want)

**Comment by levenc** [comment]
Thank you for your interest in `posologyr`! That would be great indeed.
Unfortunately I won't be able to make it to the PAGE summit this year, but I appreciate your invitation. 
I'm going to take a closer look at `nonmem2rx` first. This will give me a better idea of how to use it with `posologyr`.

**Comment by mattfidler** [comment]
If you want to meet virtually after page we could as well.

**Comment by levenc** [comment]
Gladly. Apologies for the slow response, I've been busy the last few days.

If it is convenient for you, we can exchange e-mails to organize this (&#x63;&#x79;&#x72;&#x69;&#x6c;&#x2e;&#x6c;&#x65;&#x76;&#x65;&#x6e;&#x20;&#x61;&#x74;&#x20;univ&#x2d;&#x62;&#x72;&#x65;&#x73;&#x74;&#x2e;&#x66;&#x72;).

**Comment by mattfidler** [comment]
Hi @levenc 

We were thinking of submitting a tutorial for nlmixr2 that includes posologyr.  Are you going to be going to ACoP?  If so would you like to present?  If not, would you mind one of us presenting for you?  Perhaps you already have some material?

Best

Matt

**Comment by levenc** [comment]
Hi @mattfidler 

I won't be attending the ACoP, but I have no objection to any of you presenting it. On the contrary, I'd be honored.

Other than the vignettes, I don't really have a tutorial. I have some anonymized examples of treatment adaptations I have done with posologyr as part of my work at the hospital. But I don't know if they can be useful for you.

If you want me to write or proofread something, I'd be happy to do so.

**Comment by mattfidler** [comment]
We can touch base when we decide who will teach which part.  The anonymized examples could be helpful.

**Comment by mattfidler** [comment]
I would say this issue is complete. I will close it now.
